export const BASIC_MENU_KEYS = {
  SECTION: "SECTION",
  TITLE: "TITLE",
};

export const INPUTS_TYPES = {
  SHORT_ANSWER: "SHORT_ANSWER",
  PARAGRAPH: "PARAGRAPH",
  MULTIPLE_CHOICE: "MULTIPLE_CHOICE",
  SINGLE_CHOICE: "SINGLE_CHOICE",
  SELECT: "SELECT",
  DATE: "DATE",
  TIME: "TIME",
};

export const PRE_BUILT_MENU_KEYS = {
  EMAIL: "EMAIL",
  ADDRESS: "ADDRESS",
  PHONE_NUMBER: "PHONE_NUMBER",
  CARD_INFORMATION: "CARD_INFORMATION",
  DATE_OF_BIRTH: "DATE_OF_BIRTH",
};
